# yamllint disable-line rule:line-length

dist: bionic

matrix:
  - os: linux
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - avr-libc
          - g++-7
          - gcc-avr
          - lcov
          - pkg-config
          - wget
    env:
      - MY_ENVIRONMENT="CC=gcc CXX=g++-7"
      - CODECOV_TOKEN="83bcf4c4-761f-4235-9b11-023a8be02d42"

before_install:
  - wget https://github.com/bazelbuild/bazel/releases/download/2.1.1/bazel_2.1.1-linux-x86_64.deb
  - sudo dpkg -i bazel_2.1.1-linux-x86_64.deb

script:
  - eval "${MY_ENVIRONMENT}"
  - bazel build //...
  - bazel test //...
  - bazel coverage --combined_report=lcov //...
  - genhtml bazel-out/_coverage/_coverage_report.dat --output-directory coverage
  - ./build_for_avr.sh

after_script:
  - ./scripts/push_test_coverage.sh

env:
  global:
    secure: YPqjhyeSm13L0N8/vcbG05vDwO7MgthOgK7ZVKDq9+/q/H7EJYHBVRQw5+cQ41TrbdwbXM3Jd0aABMPWscP7+/gVzEbCQGWsFYVc0Jgi8SWK2j3/xO4n78YUR6bqYP090tYM17VmPjT2BrPFpBGBPnf3kYNXcqsUsZIr72QHsMKzXPCy+7qUEONMzVC/H596RfEl9vxq6pN/NttfmZt9P+CTAA/s3yodBFJaxdXpwrUo9tUeGZHODPt/yO1LoYti5JSZhqbqqWdBwfO63yJA4vM/LogogHGiHogVmNP37QkdAZHVXmjqGzVK/qgEPU+o2sBcIPE4UlPbXe6lzrTtU6fw64Y5MvjLIknqjNOoYVRc8QtUST5agO7UST1vU3t+vAQzaEF81I7JEj1KxN3Ykb/65gtkb+T6Or1pMOhH9+YOAf8EBR1ZbNqgXkZ7DelzrVPkpiP04XqdtJq9XByPxNnjn0ZkS8ywH+iSF78sitgDBc7b1ofjgwQXXWB0ohhJ1DxY5HPr9hZDjE1hR3iL/35bBGa4OZIXtdMhOTRv+BJXl4SGMqjVz3XSQal/GlmIRE1TvDwLzZ8D9t5ZcY0urAHXBAKSKUtTlZK6WdKFenh9k+odejbgjmiFBeIkzjnBjDP5WiXwydYFb5ToO1NOLvP6oAICwUgjtgx31ou2qRg=
