name: CI

on:
  push:
    branches:
      - master

    tags:
      - v*

  pull_request:

jobs:
  gcc:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          wget https://github.com/bazelbuild/bazel/releases/download/3.4.1/bazel_3.4.1-linux-x86_64.deb
          sudo dpkg -i bazel_3.4.1-linux-x86_64.deb
          sudo apt install lcov
          sudo apt install pkg-config

      - name: Build and Test
        run: |
          bazel test --color=yes //... > >(tee -a /tmp/test.log) 2>&1
  avr-gcc:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt install \
            avr-libc \
            binutils \
            gcc-avr

      - uses: extractions/setup-just@v1
        with:
          just-version: 0.10.2  # optional semver specification, otherwise latest

      - name: Build
        run: |
          cd demo
          just build

  converage:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          wget https://github.com/bazelbuild/bazel/releases/download/3.4.1/bazel_3.4.1-linux-x86_64.deb
          sudo dpkg -i bazel_3.4.1-linux-x86_64.deb
          sudo apt install lcov
          sudo apt install pkg-config

      - name: Read secrets
        run: |
          CODECOV_TOKEN="${{ secrets.CODECOV_TOKEN }}"

      - name: Compute and publish Coverage Report
        run: |
          bazel coverage --combined_report=lcov --sandbox_base=/run/shm //...
          genhtml bazel-out/_coverage/_coverage_report.dat --output-directory coverage
          ./scripts/profiling.sh
